name: UnwrapSeedPoints
channels:
  - conda-forge
dependencies:
  - nibabel>=5.2.1
  - numpy>=1.26.4
  - pip>=24.0
  - python>=3.11.8
  - scipy>= 1.13.0
  - scikit-image>=0.22.0
  - simple-parsing>=0.1.5
